apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  labels:
    app: demo-dashboard
    component: redis-slave
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-dashboard
      component: redis-slave
      tier: backend
  template:
    metadata:
      labels:
        app: demo-dashboard
        component: redis-slave
        tier: backend
    spec:
      restartPolicy: Always
      containers:
        - name: redis-slave
          image: redis:7.2  # Same Redis version as master
          ports:
            - containerPort: 6379  # Default Redis port
          
          # Environment variable to locate the master Redis service
          env:
            - name: GET_HOSTS_FROM
              value: dns  # Use DNS to resolve the Redis master service (recommended for Minikube & EKS)
          # 'env' value is only needed if the cluster has no DNS service (rare case)
