apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: demo-dashboard
    component: redis-master
    tier: backend
spec:
  ports:
  - port: 6379       # Service port (internal cluster port)
    targetPort: 6379 # Container port where Redis is listening (default Redis port)
  selector:
    app: demo-dashboard
    component: redis-master
    tier: backend     # Matches the pod labels from Deployment
