apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  # If your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: NodePort 
  type: LoadBalancer
  ports:
    - port: 80  # External port
      #Do NOT use nodeport when using service type:LoadBalancer
  selector:
    app: guestbook
    tier: frontend
